import '~/styles/globals.css'

import { type Metadata } from 'next'
import { Geist } from 'next/font/google'

import { TRPCReactProvider } from '~/trpc/react'
import { WalletProviderComponent } from './_components/wallet-provider'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <WalletProviderComponent>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </WalletProviderComponent>
      </body>
    </html>
  )
}
